/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_matrixexample_MatrixJniStarter */

#ifndef _Included_com_test_matrixexample_MatrixJniStarter
#define _Included_com_test_matrixexample_MatrixJniStarter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_matrixexample_MatrixJniStarter
 * Method:    draw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_test_matrixexample_MatrixJniStarter_draw
  (JNIEnv *, jobject);

/*
 * Class:     com_test_matrixexample_MatrixJniStarter
 * Method:    reshape
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_test_matrixexample_MatrixJniStarter_reshape
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_test_matrixexample_MatrixJniStarter
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_test_matrixexample_MatrixJniStarter_create
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
